version: '3.8'

services:
  jira-db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=jira_development
    ports:
      - 5432:5432
    networks:
      - jira-network
    volumes:
      - ./docker-volumes/pgdata:/var/lib/postgresql/data:delegated

  jira-api:
    container_name: jira_api
    image: jira-api-prod:1.0.0
    restart: unless-stopped
    build:
      context: api
      target: production
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - jira-network
    depends_on:
      - jira-db
  
  jira-app:
    container_name: jira_app
    image: jira-app-prod:1.0.0
    restart: unless-stopped
    build:
      context: client
      target: production
      dockerfile: Dockerfile
    ports:
      - 8080:8081
    networks:
      - jira-network
    depends_on:
      - jira-api


networks:
  jira-network:

